### ISSUE TITLE
卡在了Scrcpy server is up但也没跳错误

### ISSUE THREAD

**Issue by teiyanesu** [TheFunny/ArisuAutoSweeper#14]
抱歉想请问卡在这段是出了什么问题?  有什么特别需要设定的吗?
使用蓝叠5模拟器
INFO     23:14:58.405 │ [u2.Device] Device(atx_agent_url=http://127.0.0.1:59402)   
INFO     23:14:58.421 │ [Device Orientation] 0 (Normal)                            
INFO     23:14:58.422 │ [Screen_size] 720x1280                                     
INFO     23:14:58.423 │ <<< SCRCPY SERVER START >>>                                
INFO     23:14:58.428 │ Create server stream                                       
INFO     23:14:58.526 │ b'[server] INFO: Device: samsung SM-S901E (Android 11)\n'  
INFO     23:14:58.528 │ Create video socket                                        
INFO     23:14:58.633 │ Create control socket                                      
INFO     23:14:58.635 │ Fetch device info                                          
INFO     23:14:58.637 │ [Scrcpy Device] SM-S901E                                   
INFO     23:14:58.637 │ [Scrcpy Resolution] (1280, 720)                            
INFO     23:14:58.637 │ Start video stream loop thread                             
INFO     23:14:58.638 │ Scrcpy server is up 

-補充截圖
![螢幕擷取畫面 2024-01-02 001022](https://github.com/TheFunny/ArisuAutoSweeper/assets/134279200/532f2f06-776f-40ee-8369-93e3fb6f465f) 

[2024-01-02_aas.txt](https://github.com/TheFunny/ArisuAutoSweeper/files/13805215/2024-01-02_aas.txt)

**Comment by RedDeadDepresso** [comment]
No, it's normal. It happens when AAS is still running but there are no active tasks.

**Comment by teiyanesu** [comment]
Thank you , but what should I do if it gets stuck when I’m doing the activity tasks?

**Comment by RedDeadDepresso** [comment]
Usually, it happens when you come across an unexpected page that the script was designed for or you have entered invalid inputs into the settings.

You can check your settings again, click Start in AAS and/or restart Blue Archive. If this does not solve the problem, a text file and a screenshot are generated in log/error. You can open an issue on Github and attach them.

**Comment by teiyanesu** [comment]
It seems to happen all the time. When I switch to another task after temporarily turning off Cafe, the same problem occurs.

Note: I’m also using ALAS at the same time. Could this be the reason?

**Comment by RedDeadDepresso** [comment]
There should be no problem running AAS alongside ALAS as I do it often. Sometimes, AAS does not detect any changes to the configuration and so you need to clear the next run section of the next task to force it to run.

**Comment by teiyanesu** [comment]
I turned everything off and found that Dashbord upd is not being captured, and there is no error log generated after I restarted.

**Comment by RedDeadDepresso** [comment]
I looked at the log you sent and it appears that the serial and emulator language are set to auto. 
Try changing them to your emulator address and language to Japanese. 
If that doesn't work, you can try other blue archive scripts like BAAH and baas, both support JP.
https://github.com/sanmusen214/BAAH
https://github.com/baas-pro/baas

**Comment by teiyanesu** [comment]
ok,thank you!
